import path from "path"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const dir = path.resolve(__dirname, "..")

process.chdir(dir)

const snapshotPath = path.join(dir, "src/provider/models-snapshot.js")

async function loadBundledSnapshot() {
  const file = Bun.file(snapshotPath)
  if (!(await file.exists())) return
  const mod = await import(`${snapshotPath}?fallback=${Date.now()}`).catch(() => undefined)
  if (!mod?.snapshot) return
  return JSON.stringify(mod.snapshot)
}

const modelsUrl = process.env.OPENCODE_MODELS_URL || "https://models.dev"
// Fetch and generate models.dev snapshot
const modelsData = process.env.MODELS_DEV_API_JSON
  ? await Bun.file(process.env.MODELS_DEV_API_JSON).text()
  : await fetch(`${modelsUrl}/api.json`)
      .then((x) => {
        if (!x.ok) throw new Error(`Failed to fetch ${modelsUrl}/api.json: ${x.status}`)
        return x.text()
      })
      .catch(async (error) => {
        const bundled = await loadBundledSnapshot()
        if (!bundled) throw error
        console.warn(`Failed to fetch ${modelsUrl}/api.json, using bundled models snapshot instead.`)
        return bundled
      })
await Bun.write(
  snapshotPath,
  `// @ts-nocheck\n// Auto-generated by build.ts - do not edit\nexport const snapshot = ${modelsData}\n`,
)
await Bun.write(
  path.join(dir, "src/provider/models-snapshot.d.ts"),
  `// Auto-generated by build.ts - do not edit\nexport declare const snapshot: Record<string, unknown>\n`,
)
console.log("Generated models-snapshot.js")
